### ISSUE TITLE
WHYYYY

### ISSUE THREAD

**Issue by ewang24** [Sashaboy97/TheSubaruDeathGame#1]
IT'S THE SUBAR DEATH GAME I CAN EDIT YOUR COMMENT MUHAHAHA

**Comment by Sashaboy97** [comment]
WHYYYYYYYYYYYYYY

**Comment by ewang24** [comment]
WHYYYYYYYYYYYYYYYYY

**Comment by ewang24** [comment]
NOOOOO DON'T EDIT MY COMMENT

yes edit ALL the comments

**Comment by ewang24** [comment]
FINE THEN I'LL JUST CLOSE THE ISSUE
